### PR TITLE
fix: #154 and #155

### LINKED ISSUE #154: [BUG] Trigger for Whitespace
### Describe the bug

The bot triggers a warning for the word `whitespace`

Add the word to the whitelist 

### To Reproduce

Type `whitespace` with the bot in your server

### Expected Behavior

_No response_

### Screenshot/ Video

Screenshot_20220103-213843_Discord

### Desktop (please complete the following information)

_No response_

### Additional context

_No response_

### LINKED ISSUE #155: [BUG] use of undefined variable
### Describe the bug

In this file `customMessage` is being used which is actually an undefined variable in the codebase and because of this its failing atleast for me when I run the bot locally on my discord server.

### To Reproduce

1. Run the bot locally according to the instructions given in the root folder readme.
2. Try out the bot on your server by sending messages with restricted words and for warnings.
3. You will get an error in your terminal/command line that the app has crashed and `customMessage` is undefined.

### Expected Behavior

Instead of `customMessage`, use `warningMessage` which is defined in the file.

### Screenshot/ Video

bot

### Desktop (please complete the following information)

Device - Lenovo Legion Y530
OS - Arch Linux
Browser - Firefox/Discord
Version - Linux 5.15.12-arch1-1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by genzyy**
## add whitespace to whitelist and fix use of undefined variable

# Description

- Added `whitespace` to whitelist so the bot doesn't give warning messages.
- Fixed use of undefined variable `customMessage` and use `warningMessage` instead which is defined and should have been used.

- Closes #154
- Closes #155

## Check List (mark all applicable checkboxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

### CODE REVIEW

**Review by SiddhantKhisty — CHANGES_REQUESTED** [review]
Looks good. I just found another word that can be added.
Please add the word `ques` as well.

**Comment by genzyy** [comment]
> Looks good. I just found another word that can be added. Please add the word `ques` as well.

Sure!

**Comment by genzyy** [comment]
Whitelisted `ques`.

**Review by SiddhantKhisty — APPROVED** [review]
LGTM

**Pull request merged**
